language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install flake8 pytest-cov
  - pip install pytest --upgrade
  - pip install . --no-cache-dir
script: pytest tests/tests.py
before_script:
  - flake8 similaritymeasures
  - pytest --version
after_success:
  - pip install python-coveralls
  - coveralls