language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install flake8 pytest
  - pip install . --no-cache-dir
script: pytest tests.py
before_script:
  - flake8 similaritymeasures
  - pytest --version
  - cd tests